# Generated by Django 5.0.1 on 2024-08-05 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
        ('user', '0002_rename_user_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
